import { StatusCode } from "../HTTPSStatusCode/StatusCode.js";
import { pool, sql } from "../DataBaseConnections/dbconnection.js";
import { checkToken, SystemError } from "../shared/functionality.js";
import { z } from "zod";


export const getItem = async (req, res) => {
  const itemId = Number(req.query.item_id);

  try {
    const token = req.headers.authorization;
    if (!token) {
      throw new SystemError("إنتهت صلاحية الجلسة , الرجاء تسجيل الدخول مرة أخرى", 401);
    }
    await checkToken(token);

    const itemResult = await pool.request()
      .input("id", itemId)
      .query(`
        SELECT *
        FROM items
        WHERE id = @id  
      `)
      ;
    const item = itemResult.recordset[0];


    return res.status(200).json({
      success: true,
      item: item,
    });

  } catch (e) {
    if (e?.originalError?.info?.message?.includes("Violation of UNIQUE KEY constraint")) {
      return res.status(409).json({
        message: "إسم الصنف موجود مسبقأ الرجاء إدخال إسم آخر"
      });
    }
    return res.status(e.status || 500).json({
      success: false,
      message: e.message || "حدث خطأ غير معروف",
    });
  }
}



export const addItem = async (req, res) => {
  const transaction = new sql.Transaction(pool);
  let transactionStarted = false;
  try {
    const token = req.headers.authorization;
    if (!token) {
      throw new SystemError("إنتهت صلاحية الجلسة , الرجاء تسجيل الدخول مرة أخرى", 401);
    }

    await checkToken(token);

    const body = req.body;


    const result = addProductSchema.parse(body);



    await transaction.begin();
    transactionStarted = true;

    const insertedItemId = await createNewItem(result.product, transaction);

    await addItemUnits(insertedItemId, result.units, transaction);

    const costPricePerUnit = calculateCostPricePerUnit(result.purchase, result.units);

    await batchStockForItem(insertedItemId, result.product.stock_quantity, costPricePerUnit, transaction);

    await transaction.commit();

    return res.status(200).json({
      success: true,
      message: "تم إنشاء الصنف بنجاح",
    });
  } catch (e) {
    if (transactionStarted) {
      try {
        await transaction.rollback();
      } catch (err) {
        console.error(err);
      }
    }

    if (e?.originalError?.info?.message?.includes("Violation of UNIQUE KEY constraint")) {
      return res.status(409).json({
        message: "إسم الصنف موجود مسبقأ الرجاء إدخال إسم آخر"
      });
    }

    const validationErrors = e?.errors || e?.issues;

    if (Array.isArray(validationErrors) && validationErrors.length > 0) {
      return res.status(400).json({
        success: false,
        message: validationErrors[0].message
      });
    }

    return res.status(e.status || 500).json({
      success: false,
      message: e.message || "حدث خطأ غير معروف",
    });
  }
}



export const updateItem = async (req, res) => {
  const itemId = Number(req.query.item_id);
  const transaction = new sql.Transaction(pool);
  try {
    const token = req.headers.authorization;
    if (!token) {
      throw new SystemError("إنتهت صلاحية الجلسة , الرجاء تسجيل الدخول مرة أخرى", 401);
    }
    await checkToken(token);

    const body = req.body;

    const needToAutoGeneratedBarcode = body.auto_generated_barcode === "1";

    let barcode;


    const schema = buildProductSchema(false);

    const rawData = {
      name: body.name,
      category_id: body.category_id,
      price: body.price || null,
      barcode: body.barcode,
      stock: Number(body.stock) || 0,
    };
    const validated = schema.safeParse(rawData);

    if (!validated.success) {
      const errors = validated.error.issues.map((err) => ({
        field: err.path.join("."),
        message: err.message,
      }));

      return res.status(400).json({
        success: false,
        errors,
      });
    }

    barcode = validated.data.barcode;


    if (barcode) {
      const existItem = await checkBarcode(barcode);
      if (existItem && existItem.id !== itemId) {
        throw new SystemError("خطأ : الباركود المدخل مُعرف لصنف آخر , الرجاء إدخال باركود مختلف ", 409);
      }
    }


    if (needToAutoGeneratedBarcode) {
      barcode = await generateUniqueBarcode()
    }

    await transaction.begin();


    await transaction.request()
      .input("name", sql.NVarChar, validated.data.name)
      .input("barcode", sql.NVarChar, barcode)
      .input("stock", sql.Int, validated.data.stock)
      .input("category_id", sql.Int, validated.data.category_id)
      .input("price", sql.Decimal(10, 2), validated.data.price)
      .input("id", sql.Int, itemId)
      .query(`
        UPDATE items
        SET name = @name, barcode = @barcode, category_id = @category_id, price = @price, stock = @stock
        WHERE id = @id
      `)
      ;


    await transaction.commit();

    return res.status(StatusCode.Ok).json({
      message: "تم تعديل الصنف بنجاح"
    });

  } catch (e) {
    try {
      await transaction.rollback();
    } catch (err) {
      console.error(err);
    }


    if (e?.originalError?.info?.message?.includes("Violation of UNIQUE KEY constraint")) {
      return res.status(409).json({
        message: "إسم الصنف موجود مسبقأ الرجاء إدخال إسم آخر"
      });
    }

    return res.status(e.status || 500).json({
      success: false,
      message: e.message || "حدث خطأ غير معروف",
    });
  }
}


export const deleteItem = async (req, res) => {
  const itemId = Number(req.query.item_id);
  try {
    const token = req.headers.authorization;
    if (!token) {
      throw new SystemError("إنتهت صلاحية الجلسة , الرجاء تسجيل الدخول مرة أخرى", 401);
    }
    await checkToken(token);
    await pool.request()
      .input("id", sql.Int, itemId)
      .query(`
        DELETE FROM items 
        WHERE id = @id
      `)
      ;
    return res.status(200).json({
      message: "تم حذف الصنف بنجاح"
    });

  } catch (e) {
    const status = e.status || 500;
    const message = e.message || "حدث خطأ غير معروف";
    return res.status(status).json({
      success: false,
      message: e.message || "حدث خطأ غير معروف"
    });
  }
}


export const filterItemsByCategory = async (req, res) => {
  const categoryId = Number(req.query.category_id);
  try {
    const token = req.headers.authorization;

    if (!token) {
      return res.status(401).json({
        message: "إنتهت صلاحية الجلسة , الرجاء تسجيل الدخول مرة أخرى"
      });
    }

    await checkToken(token);

    const result = await pool.request().query(`
      SELECT * 
      FROM items
      WHERE category_id = ${categoryId}
    `);

    let items = result.recordset;


    return res.status(200).json(items);

  } catch (e) {
    return res.status(e.status || 500).json({
      success: false,
      message: e.message || "حدث خطأ غير معروف"
    });
  }

}


export const getAllItems = async (req, res) => {
  try {
    const token = req.headers.authorization;

    if (!token) {
      return res.status(401).json({
        message: "إنتهت صلاحية الجلسة , الرجاء تسجيل الدخول مرة أخرى"
      });
    }

    await checkToken(token);

    const result = await pool.request().query(`
      SELECT * 
      FROM items
      ORDER BY name ASC
    `);

    let items = result.recordset;

    return res.status(200).json({ items });

  } catch (e) {
    return res.status(e.status || 500).json({
      success: false,
      message: e.message || "حدث خطأ غير معروف"
    });
  }
}

export const getMenueTree = async (req, res) => {
  try {
    const token = req.headers.authorization;

    if (!token) {
      return res.status(401).json({
        message: "إنتهت صلاحية الجلسة , الرجاء تسجيل الدخول مرة أخرى"
      });
    }

    const adminId = await checkToken(token);

    const result = await pool.request()
      .input('admin_id', sql.Int, adminId)
      .query(`
        SELECT
          mc.id   AS maincategory_id,
          mc.name AS maincategory_name,

          c.id    AS category_id,
          c.name  AS category_name,

          i.id    AS item_id,
          i.name  AS item_name,
          i.price AS item_price,
        
          i.barcode AS item_barcode,

          s.id    AS size_id,
          s.name  AS size_name,
          s.price AS size_price

        FROM Main_category mc
          JOIN admin a ON a.id = mc.admin_id AND a.status = 1
          JOIN categories c ON c.main_category_id = mc.id
          JOIN Items i ON i.category_id = c.id
          LEFT JOIN sizes s ON s.item_id = i.id
        WHERE 
          mc.admin_id = @admin_id
        ORDER BY mc.id, c.id, i.id, s.price ASC;
      `)
      ;

    const row = result.recordset;
    const menue = buildMenuTree(row);

    return res.status(200).json(menue);


  } catch (e) {
    return res.status(e.status || 500).json({
      success: false,
      message: e.message || "حدث خطأ غير معروف"
    });
  }

}

export const getItemUnitTreeForSupplier = async (req, res) => {
  try {
    const token = req.headers.authorization;

    if (!token) {
      return res.status(401).json({
        message: "إنتهت صلاحية الجلسة , الرجاء تسجيل الدخول مرة أخرى"
      });
    }

    await checkToken(token);

    const result = await pool.request()
      .query(`
        SELECT
          i.id,
          i.name,
          i.category_id,

          iu.id AS unit_id,
          iu.unit_name,
          iu.for_purchase,
          iu.barcode,
          iu.conversion_factor,

          sb.cost_price AS last_cost_price

        FROM items i

        INNER JOIN items_units iu
            ON iu.item_id = i.id

        OUTER APPLY (
            SELECT TOP 1
                cost_price
            FROM stock_batches sb
            WHERE sb.item_id = i.id
            ORDER BY sb.id DESC
        ) sb

        ORDER BY i.name ASC;
    `);

    const itemsData = buildItemsDataForSupplier(result);
    return res.status(200).json(itemsData);


  } catch (e) {
    return res.status(e.status || 500).json({
      success: false,
      message: e.message || "حدث خطأ غير معروف"
    });
  }

}


export const getItemUnitTreeForCashier = async (req, res) => {
  try {
    const token = req.headers.authorization;

    if (!token) {
      return res.status(401).json({
        message: "إنتهت صلاحية الجلسة , الرجاء تسجيل الدخول مرة أخرى"
      });
    }

    await checkToken(token);

    const result = await pool.request()
      .query(`
        SELECT
          i.id,
          i.name,
          i.category_id,

          iu.id AS unit_id,
          iu.unit_name,
          iu.barcode,
          iu.conversion_factor,
          iu.price

        FROM items i

        INNER JOIN items_units iu
            ON iu.item_id = i.id
        WHER iu.for_sale =1

        ORDER BY i.name ASC, iu.id ASC;
    `);

    const itemsData = buildItemsDataForCashier(result);
    return res.status(200).json(itemsData);


  } catch (e) {
    return res.status(e.status || 500).json({
      success: false,
      message: e.message || "حدث خطأ غير معروف"
    });
  }

}



async function addItemUnits(itemId, units, transaction) {

  if (!Array.isArray(units) || units.length === 0) {
    return;
  }

  const MAX_RETRIES = 10;

  const manualBarcodes = units
    .filter(unit =>
      !unit.auto_generated_barcode &&
      unit.barcode
    )
    .map(unit => String(unit.barcode));

  const uniqueManualBarcodes = new Set();

  for (const barcode of manualBarcodes) {

    if (uniqueManualBarcodes.has(barcode)) {

      throw new SystemError(
        `خطأ : الباركود المدخل "${barcode}" مكرر , الرجاء إدخال باركود مختلف`,
        409
      );
    }

    uniqueManualBarcodes.add(barcode);
  }

  if (manualBarcodes.length > 0) {

    const request = transaction.request();

    const barcodeParams = manualBarcodes.map((barcode, index) => {

      request.input(
        `manual_barcode_${index}`,
        sql.VarChar(50),
        barcode
      );

      return `@manual_barcode_${index}`;
    });


    const result = await request.query(`
            SELECT TOP 1 barcode
            FROM items_units
            WHERE barcode IN (${barcodeParams.join(', ')})
        `);


    if (result.recordset.length > 0) {

      const duplicateBarcode = String(
        result.recordset[0].barcode
      );

      throw new SystemError(
        `خطأ : الباركود المدخل "${duplicateBarcode}" مُعرف لصنف آخر , الرجاء إدخال باركود مختلف`,
        409
      );
    }
  }


  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {

    const usedBarcodes = new Set(manualBarcodes);

    const preparedUnits = units.map(unit => {

      let barcode = unit.barcode
        ? String(unit.barcode)
        : null;


      let isGenerated = false;

      if (unit.auto_generated_barcode) {

        do {

          barcode = generateBarcode();

        } while (usedBarcodes.has(barcode));


        usedBarcodes.add(barcode);

        isGenerated = true;
      }


      return {
        unit_name: unit.unit_name,
        item_id: itemId,
        conversion_factor: unit.conversion_factor,
        barcode,
        price: unit.selling_price,
        for_sale: unit.for_sale ? 1 : 0,
        for_purchase: unit.for_purchase ? 1 : 0,
        isGenerated
      };
    });

    const request = transaction.request();

    request.input(
      'item_id',
      sql.Int,
      itemId
    );


    const values = preparedUnits.map((unit, index) => {

      request.input(
        `unit_name_${index}`,
        sql.NVarChar(255),
        unit.unit_name
      );

      request.input(
        `conversion_factor_${index}`,
        sql.Decimal(18, 6),
        unit.conversion_factor
      );

      request.input(
        `barcode_${index}`,
        sql.VarChar(50),
        unit.barcode
      );

      request.input(
        `price_${index}`,
        sql.Decimal(18, 2),
        unit.price
      );

      request.input(
        `for_sale_${index}`,
        sql.Bit,
        unit.for_sale
      );

      request.input(
        `for_purchase_${index}`,
        sql.Bit,
        unit.for_purchase
      );


      return `(
                @unit_name_${index},
                @item_id,
                @conversion_factor_${index},
                @barcode_${index},
                @price_${index},
                @for_sale_${index},
                @for_purchase_${index}
            )`;
    });


    const query = `
            INSERT INTO items_units (
                unit_name,
                item_id,
                conversion_factor,
                barcode,
                price,
                for_sale,
                for_purchase
            )
            VALUES
                ${values.join(',\n')}
        `;


    try {

      await request.query(query);

      return preparedUnits;

    } catch (error) {

      const isDuplicateError =
        error.number === 2601 ||
        error.number === 2627;

      if (!isDuplicateError) {
        throw error;
      }
      const generatedCollisionPossible = preparedUnits.some(
        unit => unit.isGenerated
      );

      if (!generatedCollisionPossible) {
        const checkRequest = transaction.request();

        const params = manualBarcodes.map((barcode, index) => {

          checkRequest.input(
            `check_barcode_${index}`,
            sql.VarChar(50),
            barcode
          );

          return `@check_barcode_${index}`;
        });

        const duplicateResult = await checkRequest.query(`
                    SELECT TOP 1 barcode
                    FROM items_units
                    WHERE barcode IN (${params.join(', ')})
                `);

        if (duplicateResult.recordset.length > 0) {

          const duplicateBarcode = String(
            duplicateResult.recordset[0].barcode
          );

          throw new SystemError(
            `خطأ : الباركود المدخل "${duplicateBarcode}" مُعرف لصنف آخر , الرجاء إدخال باركود مختلف`,
            409
          );
        }
      }
      if (attempt === MAX_RETRIES) {

        throw new SystemError(
          "خطأ : تعذر إنشاء باركود فريد تلقائياً , الرجاء المحاولة مرة أخرى",
          409
        );
      }
    }
  }
}


function calculateCostPricePerUnit(purchase, units) {
  const purchaseUnit = units.find(u => u.id === purchase.unit_id);

  if (!purchaseUnit) {
    throw new SystemError(
      "خطأ : وحدة الشراء غير موجودة ضمن وحدات المنتج",
      400
    );
  }

  const price = Number(purchase.price);
  const conversionFactor = Number(purchaseUnit.conversion_factor);


  if (!Number.isFinite(price) || price < 0) {
    throw new SystemError(
      "خطأ : سعر الشراء غير صالح",
      400
    );
  }

  if (!Number.isFinite(conversionFactor) || conversionFactor <= 0) {
    throw new SystemError(
      "خطأ : معامل التحويل يجب أن يكون أكبر من صفر",
      400
    );
  }

  const costPricePerBaseUnit = price / conversionFactor;

  if (!Number.isFinite(costPricePerBaseUnit)) {
    throw new SystemError(
      "خطأ : تعذر حساب سعر التكلفة",
      400
    );
  }

  return costPricePerBaseUnit;
}






async function checkBarcode(barcode) {
  const result = await pool
    .request()
    .input('barcode', barcode)
    .query(`
      SELECT id
      FROM items
      WHERE barcode = @barcode
    `);
  return result.recordset[0];
}

function generateBarcode() {
  return Math.floor(100000000 + Math.random() * 900000000).toString();
}


async function createNewItem(item, transaction) {
  const result = await transaction
    .request()
    .input("name", sql.NVarChar, item.name)
    .input("category_id", sql.Int, item.category_id)
    .input("stock", sql.Decimal(20, 3), item.stock_quantity)

    .input("admin_id", sql.Int, item.admin_id)
    .query(`
      INSERT INTO items (name, category_id, stock)
      OUTPUT INSERTED.id
      VALUES (@name, @category_id, @stock)
    `)
    ;


  return result.recordset[0].id;
}

async function generateUniqueBarcode() {
  let barcode;
  const generatedBarcodes = new Map();

  while (true) {
    barcode = generateBarcode();

    if (generatedBarcodes.has(barcode)) {
      continue;
    }
    generatedBarcodes.set(barcode, true);

    const item = await checkBarcode(barcode);
    if (!item) {
      return barcode;
    }
  }
}

async function batchStockForItem(itemId, stock, cost_price, transaction) {

  await transaction.request()
    .input("item_id", sql.Int, itemId)
    .input("quantity", sql.Decimal(18, 3), stock)
    .input('cost_price', sql.Decimal(18, 3), cost_price)
    .query(`
      INSERT INTO stock_batches (item_id, quantity, remaining_qty, cost_price)
      VALUES (@item_id, @quantity, @quantity, @cost_price)
    `);

}







function buildMenuTree(rows) {
  const mainCategoriesMap = {};
  const itemsMap = {};

  if (!rows || rows.length === 0) {
    return { mainCategories: [], items: [] };
  }

  for (const row of rows) {

    /* ---------- Main Category ---------- */
    if (!mainCategoriesMap[row.maincategory_id]) {
      mainCategoriesMap[row.maincategory_id] = {
        id: row.maincategory_id,
        name: row.maincategory_name,
        categories: {}
      };
    }

    const mainCategory = mainCategoriesMap[row.maincategory_id];

    /* ---------- Category ---------- */
    if (!mainCategory.categories[row.category_id]) {
      mainCategory.categories[row.category_id] = {
        id: row.category_id,
        name: row.category_name
      };
    }

    /* ---------- Item (Global List) ---------- */
    if (!itemsMap[row.item_id]) {
      itemsMap[row.item_id] = {
        id: row.item_id,
        name: row.item_name,
        price: row.item_price,
        barcode: row.item_barcode,
        category_id: row.category_id,
        sizes: []
      };
    }

    const item = itemsMap[row.item_id];

    /* ---------- Sizes ---------- */
    if (row.size_id) {
      item.sizes.push({
        id: row.size_id,
        name: row.size_name,
        price: row.size_price
      });
    }
  }

  return {
    mainCategories: Object.values(mainCategoriesMap).map(mc => ({
      id: mc.id,
      name: mc.name,
      categories: Object.values(mc.categories)
    })),
    items: Object.values(itemsMap)
  };
}


function buildItemsDataForSupplier(result) {

  const itemsMap = new Map();

  for (const row of result.recordset) {

    let item = itemsMap.get(row.id);

    if (!item) {
      item = {
        id: row.id,
        category_id: row.category_id,
        name: row.name,
        barcode: [],
        units: [],
        cost_price: row.last_cost_price
      };
      itemsMap.set(row.id, item);
    }


    if (row.barcode !== null && !item.barcode.includes(row.barcode)) {
      item.barcode.push(row.barcode);
    }


    if (row.for_purchase && !item.units.some(unit => unit.name === row.unit_name)) {
      item.units.push({
        id: row.unit_id,
        name: row.unit_name,
        conversion_factor: row.conversion_factor
      });
    }
  }

  return Array.from(itemsMap.values());
}

function buildItemsDataForCashier(result) {

  const itemsMap = new Map();

  for(const row of result.recordset) {

    let item = itemsMap.get(row.id);

    if (!item) {
      item = {
        id: row.id,
        category_id: row.category_id,
        name: row.name,
        units: [],
      };
      itemsMap.set(row.id, item);
    }


    if (!item.units.some(unit => unit.id === row.unit_id)) {
      item.units.push({
        id: row.unit_id,
        name: row.unit_name,
        price : row.price,
        barcode: row.barcode,
        conversion_factor: row.conversion_factor
      });
    }
  }

  return Array.from(itemsMap.values());
}





function buildProductSchema(AddNewItems = true) {
  return z.object({
    name: z
      .string()
      .min(1, "اسم المنتج مطلوب")
      .regex(/^[\p{L}\p{N}\s]+$/u, "الاسم يجب أن يحتوي على حروف أو أرقام فقط"),

    stock: z
      .number()
      .min(0, "المخزون يجب أن يكون 0 أو رقمًا موجبًا"),
    barcode: z.preprocess(
      (v) => {
        if (v === null || v === undefined || v === "") return null;
        return String(v);
      },
      z.string()
        .regex(/^\d+$/, "الباركود يجب أن يحتوي على أرقام فقط")
        .max(20, "الباركود يجب ألا يتجاوز 20 رقم")
        .nullable()
        .optional()
    ),

    category_id: z.preprocess(
      (val) => {
        if (val === null) return null;

        if (typeof val === "string") {
          const trimmed = val.trim();
          if (trimmed === "") return null;
          return Number(trimmed);
        }

        return val;
      },
      z.union([
        z.number({
          invalid_type_error: "الفئة يجب أن تكون رقم",
        }),
        z.null(),
      ]).refine((val) => val !== null, {
        message: "يجب إدخال الفئة للصنف",
      })
    ),

    // -------- السعر --------
    price:
      z.preprocess(
        (v) => {
          if (v === null || v === undefined || v === "") return null;
          return Number(v);
        },
        z.number()
          .positive("السعر يجب أن يكون رقمًا موجبًا")
          .refine(v => v !== null, { message: "يجب إدخال سعر الصنف" })
      ),

    cost_price: AddNewItems
      ? z.preprocess(
        (v) => {
          if (v === null || v === undefined || v === "") return null;
          return Number(v);
        },
        z.number()
          .positive("سعر الشراء يجب أن يكون رقمًا موجبًا")
      )
      : z.null().optional(),
  });
}




const unitSchema = z.object({
  id: z.string()
    .min(1, "معرف الوحدة مطلوب"),

  unit_name: z.string()
    .trim()
    .min(1, "اسم الوحدة مطلوب")
    .max(100, "اسم الوحدة طويل جداً"),

  contains_quantity: z.number()
    .positive("كمية الوحدة يجب أن تكون أكبر من صفر")
    .nullable(),

  contains_unit_id: z.string()
    .min(1, "الوحدة المحتواة مطلوبة")
    .nullable(),

  contains_unit_name: z.string()
    .trim()
    .min(1, "اسم الوحدة المحتواة مطلوب")
    .nullable(),

  conversion_factor: z.number()
    .positive("معامل التحويل يجب أن يكون أكبر من صفر"),

  barcode: z.string()
    .trim()
    .regex(
      /^\d+$/,
      "الباركود يجب أن يحتوي على أرقام فقط"
    )
    .max(50, "الباركود طويل جداً")
    .nullable(),

  selling_price: z.number()
    .nonnegative("سعر البيع لا يمكن أن يكون سالباً"),

  for_sale: z.boolean(),
  for_purchase: z.boolean(),
  auto_generated_barcode: z.boolean(),
  is_base_unit: z.boolean()
});

const productSchema = z.object({
  name: z.string()
    .trim()
    .min(2, "اسم المنتج يجب أن يحتوي على حرفين على الأقل")
    .max(150, "اسم المنتج طويل جداً"),

  category_id: z.number()
    .int("معرف التصنيف يجب أن يكون رقماً صحيحاً")
    .positive("معرف التصنيف غير صالح"),

  stock_quantity: z.number()
    .nonnegative("المخزون لا يمكن أن يكون سالباً")
});

const purchaseSchema = z.object({
  unit_id: z.string()
    .min(1, "وحدة الشراء مطلوبة"),

  unit_name: z.string()
    .trim()
    .min(1, "اسم وحدة الشراء مطلوب"),

  price: z.number()
    .nonnegative("سعر الشراء لا يمكن أن يكون سالباً"),

  quantity: z.number()
    .nonnegative("كمية المخزون لا يمكن أن تكون سالبة"),

  base_quantity: z.number()
    .nonnegative("كمية المخزون الأساسية لا يمكن أن تكون سالبة")
});



const addProductSchema = z.object({
  product: productSchema,
  purchase: purchaseSchema,
  units: z.array(unitSchema)
    .min(1, "يجب إضافة وحدة واحدة على الأقل")
}).superRefine((data, ctx) => {

  const { product, purchase, units } = data;

  // =========================
  // التحقق من الوحدة الأساسية
  // =========================

  const baseUnits = units.filter(unit => unit.is_base_unit);

  if (baseUnits.length !== 1) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ["units"],
      message: "يجب أن يحتوي المنتج على وحدة أساسية واحدة فقط"
    });
  }

  const baseUnit = baseUnits[0];

  if (baseUnit) {

    if (baseUnit.conversion_factor !== 1) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["units"],
        message: "معامل تحويل الوحدة الأساسية يجب أن يكون 1"
      });
    }

    if (baseUnit.contains_unit_id !== null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["units"],
        message: "الوحدة الأساسية لا يمكن أن تحتوي على وحدة أخرى"
      });
    }

    if (baseUnit.contains_quantity !== null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["units"],
        message: "الوحدة الأساسية لا يمكن أن تحتوي على كمية"
      });
    }

    if (baseUnit.contains_unit_name !== null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["units"],
        message: "الوحدة الأساسية لا يمكن أن تحتوي على وحدة"
      });
    }
  }

  // =========================
  // أسماء الوحدات
  // =========================

  const unitNames = new Set();

  for (const unit of units) {

    const normalizedName = unit.unit_name.trim().toLowerCase();

    if (unitNames.has(normalizedName)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["units"],
        message: `اسم الوحدة "${unit.unit_name}" مكرر`
      });
    }

    unitNames.add(normalizedName);
  }

  // =========================
  // الباركودات
  // =========================

  const barcodes = new Set();

  for (const unit of units) {

    if (!unit.barcode) continue;

    if (barcodes.has(unit.barcode)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["units"],
        message: `الباركود "${unit.barcode}" مستخدم أكثر من مرة`
      });
    }

    barcodes.add(unit.barcode);
  }

  // =========================
  // التحقق من الوحدات الأب
  // =========================

  const unitMap = new Map(
    units.map(unit => [unit.id, unit])
  );

  for (const unit of units) {

    if (unit.is_base_unit) continue;

    if (!unit.contains_unit_id) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["units"],
        message: `الوحدة "${unit.unit_name}" يجب أن تحتوي على وحدة`
      });

      continue;
    }

    const parentUnit = unitMap.get(unit.contains_unit_id);

    if (!parentUnit) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["units"],
        message: `الوحدة "${unit.unit_name}" تحتوي على وحدة غير موجودة`
      });

      continue;
    }

    if (!unit.contains_quantity) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["units"],
        message: `يجب تحديد كمية الوحدة "${unit.unit_name}"`
      });

      continue;
    }

    // =========================
    // حساب معامل التحويل
    // =========================

    const expectedConversion =
      unit.contains_quantity *
      parentUnit.conversion_factor;

    if (unit.conversion_factor !== expectedConversion) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["units"],
        message:
          `معامل تحويل الوحدة "${unit.unit_name}" غير صحيح`
      });
    }

    // منع الوحدة من احتواء نفسها
    if (unit.contains_unit_id === unit.id) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["units"],
        message: `الوحدة "${unit.unit_name}" لا يمكن أن تحتوي نفسها`
      });
    }
  }

  // =========================
  // التحقق من وحدة الشراء
  // =========================

  const purchaseUnit = unitMap.get(purchase.unit_id);

  if (!purchaseUnit) {

    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ["purchase", "unit_id"],
      message: "وحدة الشراء غير موجودة ضمن وحدات المنتج"
    });

  } else {

    // التحقق من اسم الوحدة
    if (purchase.unit_name !== purchaseUnit.unit_name) {

      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["purchase", "unit_name"],
        message: "اسم وحدة الشراء غير متطابق"
      });
    }

    // حساب المخزون الأساسي
    const expectedBaseQuantity =
      purchase.quantity *
      purchaseUnit.conversion_factor;

    if (purchase.base_quantity !== expectedBaseQuantity) {

      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["purchase", "base_quantity"],
        message: "كمية المخزون الأساسية غير صحيحة"
      });
    }

    // مقارنة مخزون المنتج
    if (product.stock_quantity !== purchase.base_quantity) {

      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["product", "stock_quantity"],
        message: "مخزون المنتج لا يطابق كمية المخزون الأساسية"
      });
    }
  }
});




